INSERT INTO
    shippings
    (
        createdDate,
        lastModifiedDate,
        userId,
        userName,
        userEmail,
        userPhone,
        billingStreet,
        billingCity,
        billingState,
        billingPostalCode,
        billingCountry,
        shippingStreet,
        shippingCity,
        shippingState,
        shippingPostalCode,
        shippingCountry
    )
    VALUES
    (
    	:createdDate,
        :lastModifiedDate,
        :userId,
        :userName,
        :userEmail,
        :userPhone,
        :billingStreet,
        :billingCity,
        :billingState,
        :billingPostalCode,
        :billingCountry,
        :shippingStreet,
        :shippingCity,
        :shippingState,
        :shippingPostalCode,
        :shippingCountry
    );