#%RAML 1.0 NamedExample
value:
    id: 100
    createdDate: "2024-03-18T11:26:00"
    lastModifiedDate: "2024-03-19T11:26:00"
    shipTo:
        userId: 1
        name: "Jerry Seinfeld"
        email: "jerry.seinfeld@comedyshow.com"
        phone: "(212) 555-1234"
    billingAddress:
        street: "129 West 81st Street"
        city: "New York City"
        state: "New York State"
        postalCode: "10024"
        country: "United States"   
    shippingAddress:
        street: "129 West 81st Street"
        city: "New York City"
        state: "New York State"
        postalCode: "10024"
        country: "United States"
